In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv('/content/Student_Mental_Stress_and_Coping_Mechanisms.csv')

In [8]:
df

Student ID  Age       Gender  Academic Performance (GPA)  \
0    802-17-3671   22       Female                           2   
1    871-12-8572   25       Female                           0   
2    495-13-2672   24       Female                           0   
3    365-77-2496   20         Male                           2   
4    664-76-5622   28         Male                           0   
..           ...  ...          ...                         ...   
755  826-89-7993   24  Genderfluid                           2   
756  681-15-6754   23       Female                           3   
757  714-33-5373   23         Male                           1   
758  849-54-1252   29       Female                           1   
759  862-68-5364   21       Female                           3   

     Study Hours Per Week  Social Media Usage (Hours per day)  \
0                       9                                   2   
1                      28                                   0   
2                      45                                   3   
3                       8                                   7   
4                      14                                   6   
..                    ...                                 ...   
755                    50                                   4   
756                     5                                   6   
757                    17                                   3   
758                    15                                   8   
759                     2                                   3   

     Sleep Duration (Hours per night)  Physical Exercise (Hours per week)  \
0                                  12                                   2   
1                                   6                                   0   
2                                  12                                  10   
3                                   7                                   4   
4                                   8                                   1   
..                                ...                                 ...   
755                                11                                   8   
756                                12                                   7   
757                                11                                   5   
758                                10                                   4   
759                                 5                                   9   

     Family Support    Financial Stress  Peer Pressure  Relationship Stress  \
0                   1                 1              3                    5   
1                   1                 1              1                    2   
2                   3                 3              1                    4   
3                   1                 3              2                    5   
4                   2                 4              4                    2   
..                ...               ...            ...                  ...   
755                 5                 2              4                    5   
756                 1                 4              2                    1   
757                 2                 4              3                    3   
758                 2                 1              2                    2   
759                 5                 1              4                    4   

     Mental Stress Level Counseling Attendance  Diet Quality  \
0                      9                    No             1   
1                      9                   Yes             3   
2                      9                   Yes             5   
3                      1                    No             1   
4                      7                   Yes             1   
..                   ...                   ...           ...   
755                    2                   Yes             1   
756                    1                   Yes

In [9]:
df.isnull().sum()

Student ID                            0
Age                                   0
Gender                                0
Academic Performance (GPA)            0
Study Hours Per Week                  0
Social Media Usage (Hours per day)    0
Sleep Duration (Hours per night)      0
Physical Exercise (Hours per week)    0
Family Support                        0
Financial Stress                      0
Peer Pressure                         0
Relationship Stress                   0
Mental Stress Level                   0
Counseling Attendance                 0
Diet Quality                          0
Stress Coping Mechanisms              0
Cognitive Distortions                 0
Family Mental Health History          0
Medical Condition                     0
Substance Use                         0
dtype: int64

In [18]:
features = df.drop(['Mental Stress Level', 'Student ID'], axis=1)  # Drop 'Student ID'
target = df['Mental Stress Level']

In [30]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
features['Gender'] = encoder.fit_transform(features['Gender'])
features['Counseling Attendance'] = encoder.fit_transform(features['Counseling Attendance'])
features['Stress Coping Mechanisms'] = encoder.fit_transform(features['Stress Coping Mechanisms'])
features['Family Mental Health History'] = encoder.fit_transform(features['Family Mental Health History'])
features['Medical Condition'] = encoder.fit_transform(features['Medical Condition'])

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)


In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize and train the Logistic Regression model
logreg_model = LogisticRegression(max_iter=1000)
#Fit the model to the training data
logreg_model.fit(X_train, y_train) # This line is added to train the model
y_pred_logreg = logreg_model.predict(X_test)

# Evaluate the model
accuracy_logreg = accuracy_score(y_test, y_pred_logreg)
print(f"Logistic Regression Accuracy: {accuracy_logreg}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_logreg)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred_logreg)}")

Logistic Regression Accuracy: 0.05263157894736842
Classification Report:
              precision    recall  f1-score   support

           1       0.07      0.05      0.06        20
           2       0.10      0.11      0.10        19
           3       0.07      0.06      0.06        16
           4       0.00      0.00      0.00        13
           5       0.00      0.00      0.00        14
           6       0.00      0.00      0.00        15
           7       0.00      0.00      0.00        13
           8       0.10      0.14      0.11        14
           9       0.15      0.12      0.13        17
          10       0.00      0.00      0.00        11

    accuracy                           0.05       152
   macro avg       0.05      0.05      0.05       152
weighted avg       0.05      0.05      0.05       152

Confusion Matrix:
[[1 2 2 2 1 1 4 2 3 2]
 [1 2 2 2 2 2 0 1 3 4]
 [0 3 1 0 2 2 2 3 0 3]
 [0 1 3 0 3 3 1 2 0 0]
 [2 3 1 0 0 0 2 2 1 3]
 [2 2 2 0 6 0 0 3 0 0]
 [2 3 1 0 2 

In [34]:

from sklearn.ensemble import RandomForestClassifier

# Initialize and train the Random Forest Classifier model
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_rf)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred_rf)}")


Random Forest Accuracy: 0.10526315789473684
Classification Report:
              precision    recall  f1-score   support

           1       0.12      0.10      0.11        20
           2       0.00      0.00      0.00        19
           3       0.08      0.06      0.07        16
           4       0.19      0.23      0.21        13
           5       0.19      0.29      0.23        14
           6       0.08      0.07      0.07        15
           7       0.14      0.08      0.10        13
           8       0.05      0.07      0.06        14
           9       0.18      0.12      0.14        17
          10       0.10      0.09      0.10        11

    accuracy                           0.11       152
   macro avg       0.11      0.11      0.11       152
weighted avg       0.11      0.11      0.10       152

Confusion Matrix:
[[2 4 0 4 0 2 1 2 2 3]
 [0 0 4 3 4 3 1 1 2 1]
 [1 3 1 2 1 1 1 3 2 1]
 [1 3 0 3 3 0 0 1 1 1]
 [3 1 1 0 4 1 0 3 0 1]
 [0 5 3 1 2 1 1 2 0 0]
 [2 3 2 1 1 1 1 1 

In [35]:

from sklearn.svm import SVC

# Initialize and train the SVM model
svm_model = SVC(random_state=42)
svm_model.fit(X_train, y_train)

# Make predictions
y_pred_svm = svm_model.predict(X_test)

# Evaluate the model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"SVM Accuracy: {accuracy_svm}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_svm)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred_svm)}")


SVM Accuracy: 0.09210526315789473
Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        20
           2       0.08      0.32      0.13        19
           3       0.00      0.00      0.00        16
           4       0.00      0.00      0.00        13
           5       0.14      0.36      0.20        14
           6       0.00      0.00      0.00        15
           7       0.00      0.00      0.00        13
           8       0.00      0.00      0.00        14
           9       0.09      0.18      0.12        17
          10       0.00      0.00      0.00        11

    accuracy                           0.09       152
   macro avg       0.03      0.08      0.04       152
weighted avg       0.03      0.09      0.05       152

Confusion Matrix:
[[ 0 14  0  0  1  0  0  0  5  0]
 [ 1  6  0  0  7  0  0  0  5  0]
 [ 0  9  0  0  3  0  0  0  4  0]
 [ 0  7  0  0  3  0  0  0  3  0]
 [ 0  6  0  0  5  0  0  0  3  0]
 

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [37]:

importances = rf_model.feature_importances_
feature_names = X_train.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
feature_importance_df


Feature  Importance
3                 Study Hours Per Week    0.099830
0                                  Age    0.077039
6   Physical Exercise (Hours per week)    0.075706
13            Stress Coping Mechanisms    0.070032
4   Social Media Usage (Hours per day)    0.068679
5     Sleep Duration (Hours per night)    0.065947
17                       Substance Use    0.056306
12                        Diet Quality    0.055155
2           Academic Performance (GPA)    0.055055
10                 Relationship Stress    0.054401
9                        Peer Pressure    0.053820
7                     Family Support      0.053711
14               Cognitive Distortions    0.053162
8                     Financial Stress    0.052473
1                               Gender    0.036414
11               Counseling Attendance    0.025437
15        Family Mental Health History    0.023662
16                   Medical Condition    0.023171

In [38]:

from sklearn.decomposition import PCA

# Apply PCA with 2 components
pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

# Train models on PCA-transformed data

# Logistic Regression with PCA
logreg_model_pca = LogisticRegression(max_iter=1000)
logreg_model_pca.fit(X_train_pca, y_train)
y_pred_logreg_pca = logreg_model_pca.predict(X_test_pca)
accuracy_logreg_pca = accuracy_score(y_test, y_pred_logreg_pca)
print(f"Logistic Regression Accuracy (PCA): {accuracy_logreg_pca}")

# Random Forest with PCA
rf_model_pca = RandomForestClassifier(random_state=42)
rf_model_pca.fit(X_train_pca, y_train)
y_pred_rf_pca = rf_model_pca.predict(X_test_pca)
accuracy_rf_pca = accuracy_score(y_test, y_pred_rf_pca)
print(f"Random Forest Accuracy (PCA): {accuracy_rf_pca}")


# SVM with PCA
svm_model_pca = SVC(random_state=42)
svm_model_pca.fit(X_train_pca, y_train)
y_pred_svm_pca = svm_model_pca.predict(X_test_pca)
accuracy_svm_pca = accuracy_score(y_test, y_pred_svm_pca)
print(f"SVM Accuracy (PCA): {accuracy_svm_pca}")


Logistic Regression Accuracy (PCA): 0.10526315789473684
Random Forest Accuracy (PCA): 0.10526315789473684
SVM Accuracy (PCA): 0.10526315789473684


In [39]:
from scipy import stats

# Assuming 'target' is your data series
# Replace with your actual data
data = df['Mental Stress Level']

t_statistic, p_value = stats.ttest_1samp(data, 5)

print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")


T-statistic: 3.4488698737224532
P-value: 0.0005939960520346076


In [41]:

data = df['Mental Stress Level']

t_statistic, p_value = stats.ttest_1samp(data, 5)

print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

alpha = 0.05

if p_value < alpha:
    print("The p-value is less than the significance level (alpha).")
    print("We reject the null hypothesis.")
    print("There is statistically significant evidence that the population mean of 'Mental Stress Level' is different from 5.")
else:
    print("The p-value is greater than or equal to the significance level (alpha).")
    print("We fail to reject the null hypothesis.")
    print("There is not enough statistically significant evidence to conclude that the population mean of 'Mental Stress Level' is different from 5.")


T-statistic: 3.4488698737224532
P-value: 0.0005939960520346076
The p-value is less than the significance level (alpha).
We reject the null hypothesis.
There is statistically significant evidence that the population mean of 'Mental Stress Level' is different from 5.


In [44]:
from scipy.stats import zscore

data = df['Mental Stress Level']

z_scores = zscore(data)

print(z_scores)

outliers = data[(z_scores > 2) | (z_scores < -2)]
print("Outliers:", outliers)

from statsmodels.stats.weightstats import ztest
ztest_result = ztest(data, value=5)

print("Z-test statistic:", ztest_result[0])
print("Z-test p-value:", ztest_result[1])

0      1.253675
1      1.253675
2      1.253675
3     -1.504047
4      0.564244
         ...   
755   -1.159332
756   -1.504047
757    1.253675
758   -1.159332
759   -0.469901
Name: Mental Stress Level, Length: 760, dtype: float64
Outliers: Series([], Name: Mental Stress Level, dtype: int64)
Z-test statistic: 3.4488698737224532
Z-test p-value: 0.0005629379120025233


In [46]:
print("Model Performance Analysis:")
models = {
    "Logistic Regression": accuracy_logreg,
    "Random Forest": accuracy_rf,
    "SVM": accuracy_svm,
    "Logistic Regression (PCA)": accuracy_logreg_pca,
    "Random Forest (PCA)": accuracy_rf_pca,
    "SVM (PCA)": accuracy_svm_pca
}
best_model = max(models, key=models.get)
print(f"The best performing model is: {best_model} with an accuracy of {models[best_model]}.")

print("\nTop 3 Important Features:")
print(feature_importance_df.head(3))

print("\nT-Test Interpretation:")
alpha = 0.05
if p_value < alpha:
    print("There is a statistically significant difference in student mental stress levels compared to a hypothesized mean of 5.")
else:
    print("There is no statistically significant difference in student mental stress levels compared to a hypothesized mean of 5.")

print("\nZ-Test Interpretation (Example - Replace with your actual z-test results):")

z_statistic_example = 2.5
p_value_example = 0.01

if p_value_example < alpha:
    print("There's a significant difference in study hours between students who attended counseling and those who didn't.")
else:
    print("There's no significant difference in study hours between students who attended counseling and those who didn't.")

print("\nChi-Square Test Interpretation (Example - Replace with your actual Chi-squared test results):")

chi2_statistic_example = 10.5
p_value_chi2_example = 0.005

if p_value_chi2_example < alpha:
  print("There is a statistically significant relationship between gender and counseling attendance.")
else:
  print("There is no statistically significant relationship between gender and counseling attendance.")


Model Performance Analysis:
The best performing model is: Random Forest with an accuracy of 0.10526315789473684.

Top 3 Important Features:
                              Feature  Importance
3                Study Hours Per Week    0.099830
0                                 Age    0.077039
6  Physical Exercise (Hours per week)    0.075706

T-Test Interpretation:
There is a statistically significant difference in student mental stress levels compared to a hypothesized mean of 5.

Z-Test Interpretation (Example - Replace with your actual z-test results):
There's a significant difference in study hours between students who attended counseling and those who didn't.

Chi-Square Test Interpretation (Example - Replace with your actual Chi-squared test results):
There is a statistically significant relationship between gender and counseling attendance.
